### ISSUE TITLE
Responsiv dizayn üçün qaynaqlar

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [iamrajabli/PragmatechFrontEndProject#4]
Mövzu ilə bağlı aşağıdakı qaynaqları analiz etməyə çalışın.

- **[1-ci qaynaq](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design)**
- **[2-ci qaynaq](https://youtu.be/S8dQjPf0GyM)**
- **[3-cü qaynaq](https://www.w3schools.com/css/css_rwd_mediaqueries.asp)**
- **[4-cü qaynaq](https://www.w3schools.com/css/css_rwd_images.asp)**
- **[5-ci qaynaq](https://www.w3schools.com/html/html_responsive.asp)**
- **[6-cı qaynaq](https://youtu.be/zryaHix-yFA)**

**Comment by iamrajabli** [comment]
Ehtiyac yox idi təşəkkürlər əziyyət üçün

**Comment by isbendiyarovanezrin** [comment]
Bundan sonra da bu tipli şeylərə ehtiyac olmayacaq, yoxsa sadəcə buna (bu mövzuya) yoxdur?

**Comment by iamrajabli** [comment]
Ümumiyyətlə ehtiyac yoxdur mən özüm lazım olduqca araşdırıram çox sağ olun
